#!/bin/bash

for((idx=0; idx<5; idx++)) ; do
  /sbin/service %{_tomcat} stop
  if [ $? == 0 ] ; then idx=5; else sleep 5; fi
done

# Remove the axis1-based installation 
if [ -d /var/lib/%{_tomcat}/webapps/ce-monitor ] ; then
  rm -rf /var/lib/%{_tomcat}/webapps/ce-monitor
  rm -f /etc/%{_tomcat}/Catalina/localhost/ce-monitor.xml
  rm -rf /var/cache/%{_tomcat}/work/Catalina/localhost/ce-monitor
fi

