#!/bin/bash

if [ $1 -eq 0 ] ; then

  for((idx=0; idx<5; idx++)) ; do
    /sbin/service %{_tomcat} stop
    if [ $? == 0 ] ; then idx=5; else sleep 5; fi
  done

  if [ -d /var/cemonitor ] ; then
    rm -rf /var/cemonitor
  fi
  
  if [ -d /var/lib/%{_tomcat}/webapps/ce-monitor ] ; then
    rm -rf /var/lib/%{_tomcat}/webapps/ce-monitor
  fi

  if [ -e /etc/%{_tomcat}/Catalina/localhost/ce-monitor.xml ] ; then
    rm -f /etc/%{_tomcat}/Catalina/localhost/ce-monitor.xml
  fi

fi

