#!/bin/bash

# Do not overwrite axis2-based installation
if [ ! -L /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/services/glite-ce-monitor.aar ] ; then

  cp -R /usr/share/axis2/webapp /var/lib/%{_tomcat}/webapps/ce-monitor || exit 1
  
  ln -s /usr/share/java/jclassads/cedar.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/jclassads/classad.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/argus-pep-api-java-compat.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/argus-pep-common-compat.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/canl.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/bcprov.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-common-java.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-monitor-api-java.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/glite-ce-monitor.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib
  ln -s /usr/share/java/voms-api-java.jar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/lib

%if 0%{?el6}
  # set allowLinking option for tomcat6
  mkdir /var/lib/%{_tomcat}/webapps/ce-monitor/META-INF
  echo '<Context override="true" allowLinking="true"></Context>' > /var/lib/%{_tomcat}/webapps/ce-monitor/META-INF/context.xml
%endif

  ln -s /usr/share/glite-ce-monitor/modules/glite-ce-monitor-authorization.mar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/modules
  find /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/modules -name *.mar -exec basename \\{\\} \\; > /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/modules/modules.list
  
  ln -s /usr/share/glite-ce-monitor/services/glite-ce-monitor.aar /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/services
  find /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/services -name *.aar -exec basename \\{\\} \\; > /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/services/services.list
  
fi

# Axis Servlet configuration
# customization of axis2.xml
REPLACE1='s|__CHANGE_SERVICE__|/etc/glite-ce-monitor/cemonitor-config.xml|g'
REPLACE2='s|__CHANGE_LOG4J__|/etc/glite-ce-monitor/log4j.properties|g'
  
sed "$REPLACE1 ; $REPLACE2" /etc/glite-ce-common-java/axis2.xml > /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/conf/axis2.xml
chmod 600 /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/conf/axis2.xml
chown tomcat.tomcat /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/conf/axis2.xml
# cannot use symlinks for the following files:
cp -f /etc/glite-ce-common-java/web.xml /var/lib/%{_tomcat}/webapps/ce-monitor/WEB-INF/

if [ $1 -eq 1 ] ; then  
# Creation of the back-end and log dir
  if [ ! "x`grep tomcat /etc/passwd`" == "x" ] ; then
    mkdir -p /var/cemonitor
    chown tomcat:tomcat /var/cemonitor
    chmod 755 /var/cemonitor
    
    mkdir -p /var/log/cemonitor
    chown tomcat:tomcat /var/log/cemonitor
    chmod 755 /var/log/cemonitor
  fi

  /sbin/service %{_tomcat} start

fi


